/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author joseg
 */
public class frm_principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    ArrayList<Moto> lista_moto = new ArrayList<Moto>();
    ArrayList<Automovil> lista_automovil = new ArrayList<Automovil>();
    ArrayList<Helicoptero> lista_helicoptero = new ArrayList<Helicoptero>();
    ArrayList<Avion> lista_avion = new ArrayList<Avion>();
    DefaultTableModel t_moto;
    DefaultTableModel t_automovil;
    Avion avion= new Avion();
    Helicoptero helicoptero = new Helicoptero();
    Moto moto = new Moto();
    Automovil auto = new Automovil();
    public frm_principal() {
        initComponents();
        cmb_tipo.addItem("Deportivo");
        cmb_tipo.addItem("Particular");
        cmb_tipo.addItem("Privado");
        cmb_tipo.addItem("Mecanico");
        cmb_tipo.addItem("Automatico");
        cmb_tipo.addItem("Semi-automatico");
        
        cmb_opcion.addItem("Automovil");
        cmb_opcion.addItem("Moto");
        cmb_opcion.addItem("Helicoptero");
        cmb_opcion.addItem("Avion");
        
        t_moto=new DefaultTableModel();
        //String encabezado[]={"Traccion","Cadena","Clutch","Asientos","Llantas","Placa"};
        String encabezado[]={"Traccion","Cadena","Clutch","Asientos","Llantas","Placa","Chasis","Frenos","Modelo","Marca","Linea","Motor","Color","Cilindros","Tipo","precio_venta"};
        t_moto.setColumnIdentifiers(encabezado);
        tbl_moto.setModel(t_moto);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanel_avion = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_salida = new javax.swing.JTextField();
        txt_winglet = new javax.swing.JTextField();
        txt_cabina = new javax.swing.JTextField();
        txt_zonas = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt_pilotoA = new javax.swing.JTextField();
        txt_ventanasA = new javax.swing.JTextField();
        txt_tanquesA = new javax.swing.JTextField();
        txt_asientosA = new javax.swing.JTextField();
        btn_encenderA = new javax.swing.JButton();
        btn_apagarA = new javax.swing.JButton();
        btn_despegar = new javax.swing.JButton();
        btn_AterrizarA = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jpanel_helicoptero = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_patines = new javax.swing.JTextField();
        txt_rotor = new javax.swing.JTextField();
        txt_turbinas = new javax.swing.JTextField();
        txt_helices = new javax.swing.JTextField();
        txt_asientos = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_piloto = new javax.swing.JTextField();
        txt_ventanasH = new javax.swing.JTextField();
        txt_tanques = new javax.swing.JTextField();
        btn_encenderH = new javax.swing.JButton();
        btn_apagarH = new javax.swing.JButton();
        btn_despegarH = new javax.swing.JButton();
        btn_aterrizarH = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jpanel_automovil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_traccionC = new javax.swing.JTextField();
        txt_suspension = new javax.swing.JTextField();
        txt_puertas = new javax.swing.JTextField();
        txt_llantasC = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_ventanas = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_asientosC = new javax.swing.JTextField();
        txt_placaC = new javax.swing.JTextField();
        txt_chasisC = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_frenosC = new javax.swing.JTextField();
        btn_inter1 = new javax.swing.JButton();
        btn_bloquear1 = new javax.swing.JButton();
        btn_acelerarV = new javax.swing.JButton();
        btn_frenar = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jpanel_moto = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_traccionM = new javax.swing.JTextField();
        txt_clutch = new javax.swing.JTextField();
        txt_asientosM = new javax.swing.JTextField();
        txt_cadena = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_llantasM = new javax.swing.JTextField();
        txt_placaM = new javax.swing.JTextField();
        txt_chasisM = new javax.swing.JTextField();
        txt_frenosM = new javax.swing.JTextField();
        btn_inter = new javax.swing.JButton();
        btn_bloquear = new javax.swing.JButton();
        btn_acelerar = new javax.swing.JButton();
        btn_encenderMoto = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_avion = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_helicoptero = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbl_automovil = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tbl_moto = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        cmb_opcion = new javax.swing.JComboBox<>();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_linea = new javax.swing.JTextField();
        txt_motor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_cilindros = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_venta = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel35.setText("Zonas");

        jLabel36.setText("Cabina");

        jLabel37.setText("Winglet");

        jLabel38.setText("Salida emergencia");

        jLabel39.setText("Asientos");

        jLabel40.setText("Piloto Automatico");

        jLabel41.setText("Ventanas");

        jLabel42.setText("Tanques");

        btn_encenderA.setText("Encender");
        btn_encenderA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encenderAActionPerformed(evt);
            }
        });

        btn_apagarA.setText("Apagar");
        btn_apagarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarAActionPerformed(evt);
            }
        });

        btn_despegar.setText("Despegar");
        btn_despegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_despegarActionPerformed(evt);
            }
        });

        btn_AterrizarA.setText("Aterrizar");
        btn_AterrizarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AterrizarAActionPerformed(evt);
            }
        });

        jLabel43.setText("Estas son algunas cosas que hace el avion");

        javax.swing.GroupLayout jpanel_avionLayout = new javax.swing.GroupLayout(jpanel_avion);
        jpanel_avion.setLayout(jpanel_avionLayout);
        jpanel_avionLayout.setHorizontalGroup(
            jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_avionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_avionLayout.createSequentialGroup()
                        .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_winglet, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txt_cabina)
                            .addComponent(txt_zonas)))
                    .addGroup(jpanel_avionLayout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_salida, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addGap(58, 58, 58)
                .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_asientosA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pilotoA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ventanasA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tanquesA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_AterrizarA, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_despegar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_apagarA, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_encenderA, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_avionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jpanel_avionLayout.setVerticalGroup(
            jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_avionLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txt_zonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(txt_asientosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_encenderA))
                .addGap(18, 18, 18)
                .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txt_cabina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(txt_pilotoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_apagarA))
                .addGap(18, 18, 18)
                .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txt_winglet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(txt_ventanasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_despegar))
                .addGap(18, 18, 18)
                .addGroup(jpanel_avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txt_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(txt_tanquesA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AterrizarA))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Avion", jpanel_avion);

        jLabel27.setText("Rotor antipar");

        jLabel28.setText("Patines de aterrizaje");

        jLabel29.setText("turbinas");

        jLabel30.setText("Helices");

        jLabel31.setText("Asientos");

        jLabel32.setText("Piloto Automatico");

        jLabel33.setText("Ventanas");

        jLabel34.setText("Tanques");

        btn_encenderH.setText("Encender");
        btn_encenderH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encenderHActionPerformed(evt);
            }
        });

        btn_apagarH.setText("Apagar");
        btn_apagarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarHActionPerformed(evt);
            }
        });

        btn_despegarH.setText("Despegar");
        btn_despegarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_despegarHActionPerformed(evt);
            }
        });

        btn_aterrizarH.setText("Aterrizar");
        btn_aterrizarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aterrizarHActionPerformed(evt);
            }
        });

        jLabel44.setText("Estas son algunas cosas que hace el helicoptero");

        javax.swing.GroupLayout jpanel_helicopteroLayout = new javax.swing.GroupLayout(jpanel_helicoptero);
        jpanel_helicoptero.setLayout(jpanel_helicopteroLayout);
        jpanel_helicopteroLayout.setHorizontalGroup(
            jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_helicopteroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_helicopteroLayout.createSequentialGroup()
                        .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpanel_helicopteroLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(76, 76, 76)
                                .addComponent(txt_turbinas, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                            .addGroup(jpanel_helicopteroLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_helices, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66))
                    .addGroup(jpanel_helicopteroLayout.createSequentialGroup()
                        .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_patines)
                            .addComponent(txt_rotor))))
                .addGap(45, 45, 45)
                .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_ventanasH, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(txt_piloto)
                        .addComponent(txt_tanques, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_asientos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_encenderH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_apagarH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_despegarH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aterrizarH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_helicopteroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addGap(23, 23, 23))
        );
        jpanel_helicopteroLayout.setVerticalGroup(
            jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_helicopteroLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_rotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(txt_piloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_encenderH))
                .addGap(18, 18, 18)
                .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_patines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txt_ventanasH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_apagarH))
                .addGap(18, 18, 18)
                .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txt_turbinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(txt_tanques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_despegarH))
                .addGap(18, 18, 18)
                .addGroup(jpanel_helicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_helices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aterrizarH)
                    .addComponent(jLabel31)
                    .addComponent(txt_asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Helicoptero", jpanel_helicoptero);

        jLabel1.setText("Traccion");

        jLabel2.setText("Llantas");

        jLabel3.setText("Suspension");

        jLabel4.setText("Puertas");

        jLabel21.setText("Ventanas");

        jLabel22.setText("Asientos");

        jLabel23.setText("Placa");

        jLabel24.setText("Chasis");

        jLabel25.setText("Tipo de Frenos");

        btn_inter1.setText("Intermitentes");
        btn_inter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inter1ActionPerformed(evt);
            }
        });

        btn_bloquear1.setText("Bloquear");
        btn_bloquear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bloquear1ActionPerformed(evt);
            }
        });

        btn_acelerarV.setText("Acelerar");
        btn_acelerarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acelerarVActionPerformed(evt);
            }
        });

        btn_frenar.setText("Frenar");
        btn_frenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frenarActionPerformed(evt);
            }
        });

        jLabel46.setText("Estas son algunas cosas que hace el carro");

        javax.swing.GroupLayout jpanel_automovilLayout = new javax.swing.GroupLayout(jpanel_automovil);
        jpanel_automovil.setLayout(jpanel_automovilLayout);
        jpanel_automovilLayout.setHorizontalGroup(
            jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_automovilLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jpanel_automovilLayout.createSequentialGroup()
                        .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpanel_automovilLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(55, 55, 55)
                                    .addComponent(txt_traccionC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_automovilLayout.createSequentialGroup()
                                    .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_suspension, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_asientosC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel21))
                        .addGap(59, 59, 59)
                        .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel25)
                                .addGroup(jpanel_automovilLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(42, 42, 42)))
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_placaC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_chasisC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_frenosC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_llantasC, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_automovilLayout.createSequentialGroup()
                        .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_automovilLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btn_inter1))
                            .addGroup(jpanel_automovilLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_acelerarV)
                                    .addComponent(btn_bloquear1)
                                    .addComponent(btn_frenar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );
        jpanel_automovilLayout.setVerticalGroup(
            jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_automovilLayout.createSequentialGroup()
                .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_automovilLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpanel_automovilLayout.createSequentialGroup()
                                .addComponent(txt_llantasC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_placaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(txt_chasisC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(txt_frenosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpanel_automovilLayout.createSequentialGroup()
                                .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_traccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpanel_automovilLayout.createSequentialGroup()
                                        .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txt_suspension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(txt_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel21)
                                            .addComponent(txt_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel23)))))
                    .addGroup(jpanel_automovilLayout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_inter1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_bloquear1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_acelerarV)
                        .addGap(18, 18, 18)
                        .addComponent(btn_frenar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_asientosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Automovil", jpanel_automovil);

        jLabel5.setText("Asientos");

        jLabel6.setText("Traccion");

        jLabel7.setText("Cadena");

        jLabel8.setText("Tipo de clutch");

        jLabel9.setText("Llantas");

        jLabel10.setText("Placa");

        jLabel11.setText("Chasis");

        jLabel12.setText("Tipo frenos");

        btn_inter.setText("Intermitentes");
        btn_inter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_interActionPerformed(evt);
            }
        });

        btn_bloquear.setText("Bloquear");
        btn_bloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bloquearActionPerformed(evt);
            }
        });

        btn_acelerar.setText("Acelerar");
        btn_acelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acelerarActionPerformed(evt);
            }
        });

        btn_encenderMoto.setText("Encender");
        btn_encenderMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encenderMotoActionPerformed(evt);
            }
        });

        jLabel45.setText("Estas son algunas cosas que hace la Moto");

        javax.swing.GroupLayout jpanel_motoLayout = new javax.swing.GroupLayout(jpanel_moto);
        jpanel_moto.setLayout(jpanel_motoLayout);
        jpanel_motoLayout.setHorizontalGroup(
            jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_motoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel_motoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_asientosM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_motoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_clutch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanel_motoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(60, 60, 60)
                        .addComponent(txt_cadena, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_motoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_traccionM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66)
                .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel_motoLayout.createSequentialGroup()
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38)
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_llantasM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_placaM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_motoLayout.createSequentialGroup()
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_motoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18))
                            .addGroup(jpanel_motoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(42, 42, 42)))
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_chasisM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_frenosM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_motoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn_inter))
                    .addGroup(jpanel_motoLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_acelerar)
                            .addComponent(btn_bloquear)
                            .addComponent(btn_encenderMoto))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_motoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addGap(18, 18, 18))
        );
        jpanel_motoLayout.setVerticalGroup(
            jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_motoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_motoLayout.createSequentialGroup()
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_llantasM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_inter))
                        .addGap(18, 18, 18)
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_placaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_bloquear))
                        .addGap(18, 18, 18)
                        .addComponent(btn_acelerar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_encenderMoto))
                    .addGroup(jpanel_motoLayout.createSequentialGroup()
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_traccionM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_cadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_clutch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txt_chasisM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jpanel_motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_asientosM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txt_frenosM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Moto", jpanel_moto);

        tbl_avion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbl_avion);

        jTabbedPane2.addTab("Avion", jScrollPane3);

        tbl_helicoptero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(tbl_helicoptero);

        jTabbedPane2.addTab("Helicoptero", jScrollPane8);

        tbl_automovil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(tbl_automovil);

        jTabbedPane2.addTab("Automovil", jScrollPane9);

        tbl_moto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(tbl_moto);

        jTabbedPane2.addTab("Moto", jScrollPane10);

        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jLabel13.setText("Modelo");

        jLabel14.setText("Marca");

        jLabel15.setText("Linea");

        jLabel16.setText("Motor");

        jLabel17.setText("Color");

        jLabel18.setText("Cilindros");

        jLabel19.setText("Tipo");

        jLabel20.setText("Precio venta");

        jLabel26.setText("¿Que vehiculo va a agregar?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(1, 1, 1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(cmb_opcion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(4, 4, 4)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_linea, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                                .addGap(83, 83, 83)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel17))
                                                .addGap(29, 29, 29)
                                                .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txt_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 16, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txt_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar)
                            .addComponent(cmb_opcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)))
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        String opcion=cmb_opcion.getSelectedItem().toString();
        String tipo= cmb_tipo.getSelectedItem().toString();
        
        if(opcion.equals("Moto"))
        {
            //String tipo= cmb_tipo.getSelectedItem().toString();
            Moto moto = new Moto(txt_traccionM.getText(), txt_cadena.getText(), txt_clutch.getText(), txt_asientosM.getText(), txt_llantasM.getText(), txt_placaM.getText(), txt_chasisM.getText(), txt_frenosM.getText(), txt_modelo.getText(), txt_marca.getText(), txt_linea.getText(), txt_motor.getText(), txt_color.getText(), txt_cilindros.getText(), tipo, txt_venta.getText());
            lista_moto.add(moto);
            mostrarMoto();
        }
        if(opcion.equals("Automovil"))
        {
            Automovil automovil = new Automovil(txt_traccionC.getText(), txt_suspension.getText(), txt_puertas.getText(), txt_ventanas.getText(), txt_asientosC.getText(), txt_llantasC.getText(), txt_placaC.getText(), txt_chasisC.getText(), txt_frenosC.getText(), txt_modelo.getText(), txt_marca.getText(), txt_linea.getText(), txt_motor.getText(), txt_color.getText(), txt_cilindros.getText(), tipo, txt_venta.getText());
            lista_automovil.add(automovil);
            mostrarAutomovil();
        }
       if(opcion.equals("Helicoptero"))
       {
          Helicoptero helicoptero= new Helicoptero(txt_rotor.getText(), txt_patines.getText(), txt_turbinas.getText(), txt_helices.getText(), txt_asientos.getText(), txt_piloto.getText(), txt_ventanasH.getText(), txt_tanques.getText(),txt_modelo.getText(), txt_marca.getText(), txt_linea.getText(), txt_motor.getText(), txt_color.getText(), txt_cilindros.getText(), tipo, txt_venta.getText()); 
          lista_helicoptero.add(helicoptero);
          mostrarhelicoptero();
       }
       if(opcion.equals("Avion"))
       {
           Avion avion = new Avion(txt_zonas.getText(), txt_cabina.getText(), txt_winglet.getText(), txt_salida.getText(), txt_asientosA.getText(), txt_pilotoA.getText(), txt_ventanasA.getText(), txt_tanquesA.getText(),txt_modelo.getText(), txt_marca.getText(), txt_linea.getText(), txt_motor.getText(), txt_color.getText(), txt_cilindros.getText(), tipo, txt_venta.getText());
           lista_avion.add(avion);
           mostrarAvion();
       }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_AterrizarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AterrizarAActionPerformed
        // TODO add your handling code here:
        avion.aterrizar();
    }//GEN-LAST:event_btn_AterrizarAActionPerformed

    private void btn_encenderAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encenderAActionPerformed
        // TODO add your handling code here:
        avion.encender();
    }//GEN-LAST:event_btn_encenderAActionPerformed

    private void btn_apagarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarAActionPerformed
        // TODO add your handling code here:
        avion.apagar();
    }//GEN-LAST:event_btn_apagarAActionPerformed

    private void btn_despegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_despegarActionPerformed
        // TODO add your handling code here:
        avion.despegar();
    }//GEN-LAST:event_btn_despegarActionPerformed

    private void btn_encenderHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encenderHActionPerformed
        // TODO add your handling code here:
        helicoptero.encender();
    }//GEN-LAST:event_btn_encenderHActionPerformed

    private void btn_apagarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarHActionPerformed
        // TODO add your handling code here:
        helicoptero.apagar();
    }//GEN-LAST:event_btn_apagarHActionPerformed

    private void btn_despegarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_despegarHActionPerformed
        // TODO add your handling code here:
        helicoptero.despegar();
    }//GEN-LAST:event_btn_despegarHActionPerformed

    private void btn_aterrizarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aterrizarHActionPerformed
        // TODO add your handling code here:
        helicoptero.aterrizar();
    }//GEN-LAST:event_btn_aterrizarHActionPerformed

    private void btn_interActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_interActionPerformed
        // TODO add your handling code here:
        moto.intermitentes();
    }//GEN-LAST:event_btn_interActionPerformed

    private void btn_bloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bloquearActionPerformed
        // TODO add your handling code here:
        moto.bloquear_vehiculo();
    }//GEN-LAST:event_btn_bloquearActionPerformed

    private void btn_acelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acelerarActionPerformed
        // TODO add your handling code here:
        moto.acelerar();
    }//GEN-LAST:event_btn_acelerarActionPerformed

    private void btn_encenderMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encenderMotoActionPerformed
        // TODO add your handling code here:
        moto.encender();
    }//GEN-LAST:event_btn_encenderMotoActionPerformed

    private void btn_inter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inter1ActionPerformed
        // TODO add your handling code here:
        auto.intermitentes();
    }//GEN-LAST:event_btn_inter1ActionPerformed

    private void btn_bloquear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bloquear1ActionPerformed
        // TODO add your handling code here:
        auto.bloquear_vehiculo();
    }//GEN-LAST:event_btn_bloquear1ActionPerformed

    private void btn_acelerarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acelerarVActionPerformed
        // TODO add your handling code here:
        auto.acelerar();
    }//GEN-LAST:event_btn_acelerarVActionPerformed

    private void btn_frenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frenarActionPerformed
        // TODO add your handling code here:
        auto.frenar();
    }//GEN-LAST:event_btn_frenarActionPerformed
    
    public void mostrarMoto()
    {
        String matriz_moto[][]=new String [lista_moto.size()][16];
        for(int i= 0; i<lista_moto.size();i++)
        {
            matriz_moto[i][0]=lista_moto.get(i).getTraccion();
            matriz_moto[i][1]=lista_moto.get(i).getCadena();
            matriz_moto[i][2]=lista_moto.get(i).getTipo_clutch();
            matriz_moto[i][3]=lista_moto.get(i).getAsientos();
            matriz_moto[i][4]=lista_moto.get(i).getLlantas();
            matriz_moto[i][5]=lista_moto.get(i).getPlaca();
            matriz_moto[i][6]=lista_moto.get(i).getChasis();
            matriz_moto[i][7]=lista_moto.get(i).getTipo_frenos();
            matriz_moto[i][8]=lista_moto.get(i).getModelo();
            matriz_moto[i][9]=lista_moto.get(i).getMarca();
            matriz_moto[i][10]=lista_moto.get(i).getLinea();
            matriz_moto[i][11]=lista_moto.get(i).getMotor();
            matriz_moto[i][12]=lista_moto.get(i).getColor();
            matriz_moto[i][13]=lista_moto.get(i).getCilindros();
            matriz_moto[i][14]=lista_moto.get(i).getTipo(); 
            matriz_moto[i][15]=lista_moto.get(i).getPrecio_venta();
        }
        tbl_moto.setModel(new javax.swing.table.DefaultTableModel(
            matriz_moto,
            new String [] {
                "Traccion","Cadena","Clutch","Asientos","Llantas","Placa","Chasis","Frenos","Modelo","Marca","Linea","Motor","Color","Cilindros","Tipo","precio_venta"
            }
        ));
    }
    
    
    public void mostrarAutomovil()
    {
        String matriz_Automovil[][]=new String [lista_automovil.size()][17];
        for(int i= 0; i<lista_automovil.size();i++)
        {
            matriz_Automovil[i][0]=lista_automovil.get(i).getTraccion();
            matriz_Automovil[i][1]=lista_automovil.get(i).getSuspension();
            matriz_Automovil[i][2]=lista_automovil.get(i).getPuertas();
            //matriz_Automovil[i][2]=txt_puertas.getText();
            matriz_Automovil[i][3]=lista_automovil.get(i).getVentanas();
            //matriz_Automovil[i][3]=txt_ventanas.getText();
            matriz_Automovil[i][4]=lista_automovil.get(i).getAsientos();
            matriz_Automovil[i][5]=lista_automovil.get(i).getLlantas();
            matriz_Automovil[i][6]=lista_automovil.get(i).getPlaca();
            matriz_Automovil[i][7]=lista_automovil.get(i).getChasis();
            matriz_Automovil[i][8]=lista_automovil.get(i).getTipo_frenos();
            matriz_Automovil[i][9]=lista_automovil.get(i).getModelo();
            matriz_Automovil[i][10]=lista_automovil.get(i).getMarca();
            matriz_Automovil[i][11]=lista_automovil.get(i).getLinea();
            matriz_Automovil[i][12]=lista_automovil.get(i).getMotor();
            matriz_Automovil[i][13]=lista_automovil.get(i).getColor();
            matriz_Automovil[i][14]=lista_automovil.get(i).getCilindros();
            matriz_Automovil[i][15]=lista_automovil.get(i).getTipo();
            matriz_Automovil[i][16]=lista_automovil.get(i).getPrecio_venta();
        }
        tbl_automovil.setModel(new javax.swing.table.DefaultTableModel(
            matriz_Automovil,

            new String [] {
                  "Traccion", "Suspension", "Puertas", "Ventanas", "Asientos", "Llantas", "Placa", "Chasis", "Frenos", "Modelo", "Marca", "Linea","Motor","Color","Cilindros","Tipo","precio_venta"
            }
        ));
    }
   
    public void mostrarhelicoptero()
    {
        String matriz_Helicoptero[][]=new String [lista_helicoptero.size()][16];
        for(int i= 0; i<lista_helicoptero.size();i++)
        {
            matriz_Helicoptero[i][0]=lista_helicoptero.get(i).getRotor_antipar();
            matriz_Helicoptero[i][1]=lista_helicoptero.get(i).getPatines_aterrizaje();
            matriz_Helicoptero[i][2]=lista_helicoptero.get(i).getTurbinas();
            matriz_Helicoptero[i][3]=lista_helicoptero.get(i).getHelices();
            matriz_Helicoptero[i][4]=lista_helicoptero.get(i).getAsientos();
            matriz_Helicoptero[i][5]=lista_helicoptero.get(i).getPiloto_automatico();
            matriz_Helicoptero[i][6]=lista_helicoptero.get(i).getVentanas();
            matriz_Helicoptero[i][7]=lista_helicoptero.get(i).getTanques();
            matriz_Helicoptero[i][8]=lista_helicoptero.get(i).getModelo();
            matriz_Helicoptero[i][9]=lista_helicoptero.get(i).getMarca();
            matriz_Helicoptero[i][10]=lista_helicoptero.get(i).getLinea();
            matriz_Helicoptero[i][11]=lista_helicoptero.get(i).getMotor();
            matriz_Helicoptero[i][12]=lista_helicoptero.get(i).getColor();
            matriz_Helicoptero[i][13]=lista_helicoptero.get(i).getCilindros();
            matriz_Helicoptero[i][14]=lista_helicoptero.get(i).getTipo();
            matriz_Helicoptero[i][15]=lista_helicoptero.get(i).getPrecio_venta();
        }
        tbl_helicoptero.setModel(new javax.swing.table.DefaultTableModel(
            matriz_Helicoptero,
                
            new String [] {
                  "Rotor", "patines", "turbinas", "helices", "asientos", "Piloto", "Ventanas", "Tanques", "Modelo", "Marca", "Linea","Motor","Color","Cilindros","Tipo","precio_venta"
            }
        ));
    }
    
    
    public void mostrarAvion()
    {
        String matriz_Avion[][]=new String [lista_avion.size()][16];
        for(int i= 0; i<lista_avion.size();i++)
        {
            matriz_Avion[i][0]=lista_avion.get(i).getZonas();
            matriz_Avion[i][1]=lista_avion.get(i).getCabina();
            matriz_Avion[i][2]=lista_avion.get(i).getWinglet();
            matriz_Avion[i][3]=lista_avion.get(i).getSalidas_emergencia();
            matriz_Avion[i][4]=lista_avion.get(i).getAsientos();
            matriz_Avion[i][5]=lista_avion.get(i).getPiloto_automatico();
            matriz_Avion[i][6]=lista_avion.get(i).getVentanas();
            matriz_Avion[i][7]=lista_avion.get(i).getTanques();
            matriz_Avion[i][8]=lista_avion.get(i).getModelo();
            matriz_Avion[i][9]=lista_avion.get(i).getMarca();
            matriz_Avion[i][10]=lista_avion.get(i).getLinea();
            matriz_Avion[i][11]=lista_avion.get(i).getMotor();
            matriz_Avion[i][12]=lista_avion.get(i).getColor();
            matriz_Avion[i][13]=lista_avion.get(i).getCilindros();
            matriz_Avion[i][14]=lista_avion.get(i).getTipo();
            matriz_Avion[i][15]=lista_avion.get(i).getPrecio_venta();
        }
        tbl_avion.setModel(new javax.swing.table.DefaultTableModel(
            matriz_Avion,
            new String [] {
                   "Zonas", "Cabina", "Winglet", "Salidas", "asientos", "Piloto", "Ventanas", "Tanques", "Modelo", "Marca", "Linea","Motor","Color","Cilindros","Tipo","precio_venta"
            }
        ));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AterrizarA;
    private javax.swing.JButton btn_acelerar;
    private javax.swing.JButton btn_acelerarV;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_apagarA;
    private javax.swing.JButton btn_apagarH;
    private javax.swing.JButton btn_aterrizarH;
    private javax.swing.JButton btn_bloquear;
    private javax.swing.JButton btn_bloquear1;
    private javax.swing.JButton btn_despegar;
    private javax.swing.JButton btn_despegarH;
    private javax.swing.JButton btn_encenderA;
    private javax.swing.JButton btn_encenderH;
    private javax.swing.JButton btn_encenderMoto;
    private javax.swing.JButton btn_frenar;
    private javax.swing.JButton btn_inter;
    private javax.swing.JButton btn_inter1;
    private javax.swing.JComboBox<String> cmb_opcion;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel jpanel_automovil;
    private javax.swing.JPanel jpanel_avion;
    private javax.swing.JPanel jpanel_helicoptero;
    private javax.swing.JPanel jpanel_moto;
    private javax.swing.JTable tbl_automovil;
    private javax.swing.JTable tbl_avion;
    private javax.swing.JTable tbl_helicoptero;
    private javax.swing.JTable tbl_moto;
    private javax.swing.JTextField txt_asientos;
    private javax.swing.JTextField txt_asientosA;
    private javax.swing.JTextField txt_asientosC;
    private javax.swing.JTextField txt_asientosM;
    private javax.swing.JTextField txt_cabina;
    private javax.swing.JTextField txt_cadena;
    private javax.swing.JTextField txt_chasisC;
    private javax.swing.JTextField txt_chasisM;
    private javax.swing.JTextField txt_cilindros;
    private javax.swing.JTextField txt_clutch;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_frenosC;
    private javax.swing.JTextField txt_frenosM;
    private javax.swing.JTextField txt_helices;
    private javax.swing.JTextField txt_linea;
    private javax.swing.JTextField txt_llantasC;
    private javax.swing.JTextField txt_llantasM;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_motor;
    private javax.swing.JTextField txt_patines;
    private javax.swing.JTextField txt_piloto;
    private javax.swing.JTextField txt_pilotoA;
    private javax.swing.JTextField txt_placaC;
    private javax.swing.JTextField txt_placaM;
    private javax.swing.JTextField txt_puertas;
    private javax.swing.JTextField txt_rotor;
    private javax.swing.JTextField txt_salida;
    private javax.swing.JTextField txt_suspension;
    private javax.swing.JTextField txt_tanques;
    private javax.swing.JTextField txt_tanquesA;
    private javax.swing.JTextField txt_traccionC;
    private javax.swing.JTextField txt_traccionM;
    private javax.swing.JTextField txt_turbinas;
    private javax.swing.JTextField txt_venta;
    private javax.swing.JTextField txt_ventanas;
    private javax.swing.JTextField txt_ventanasA;
    private javax.swing.JTextField txt_ventanasH;
    private javax.swing.JTextField txt_winglet;
    private javax.swing.JTextField txt_zonas;
    // End of variables declaration//GEN-END:variables
}
